---
- name: Installation de KIND sur Ubuntu 20.04
  hosts: 192.168.31.152
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/yen/.ssh/id_rsa
    ansible_become_pass: yann2024

  tasks:
    - name: Installation de Docker
      apt:
        name: docker.io
        state: present

    - name: Installation de curl
      apt:
        name: curl
        state: present

    - name: Téléchargement de KIND avec wget
      shell: wget -O /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
      args:
        creates: /usr/local/bin/kind

    - name: Attribution des droits d'exécution à KIND
      file:
        path: /usr/local/bin/kind
        mode: 'a+x'

